name = "crypto-trading-cron"
main = "cloudflare-worker.js"
compatibility_date = "2024-01-01"

[triggers]
crons = [
  # 每5分钟执行: monitor_delist + cancel_pending_limits
  "*/5 * * * *",
  # 每15分钟执行: fetch_filled_orders + auto_sell_orders
  "*/15 * * * *",
  # 每天23:54 - 取消待处理触发器
  "54 23 * * *",
  # 每天00:06 - 创建算法触发器
  "6 0 * * *"
]

[env.production]
name = "crypto-trading-cron-prod"

[env.staging]
name = "crypto-trading-cron-staging"

# 环境变量配置
[vars]
GITHUB_OWNER = "xucheng2024"
GITHUB_REPO = "crypto-trading-automation"

# 密钥配置 (需要在Cloudflare Dashboard中设置)
# GITHUB_TOKEN = "your_github_token_here"
