name = "crypto-trading-cron-prod"
main = "cloudflare-worker.js"
compatibility_date = "2024-01-01"

# 环境变量配置 (需要在Cloudflare Dashboard中设置)
# GITHUB_OWNER = "your_github_username"
# GITHUB_REPO = "your_repo_name"

# KV存储配置（用于去重）
# 需要在Cloudflare Dashboard中创建KV命名空间并设置ID
[[kv_namespaces]]
binding = "DEDUP_KV"
id = "your_kv_namespace_id"
preview_id = "your_preview_kv_namespace_id"

[triggers]
crons = [
  # 每5分钟执行: monitor_delist + cancel_pending_limits (错开整点，避免与15分钟冲突)
  "1,6,11,16,21,26,31,36,41,46,51,56 * * * *",
  # 每15分钟执行: fetch_filled_orders + auto_sell_orders (整点)
  "0,15,30,45 * * * *",
  # 每天23:55 SGT (15:55 UTC) - 取消待处理触发器
  "55 15 * * *",
  # 每天00:05 SGT (16:05 UTC) - 创建算法触发器
  "5 16 * * *"
]

# 密钥配置 (需要在Cloudflare Dashboard中设置)
# GITHUB_TOKEN = "your_github_token_here"
# GITHUB_OWNER = "your_github_username"  
# GITHUB_REPO = "your_repo_name"
